---
version: "2"

networks:
  media-server:

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - media-server
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - $HOME/media-server/config/transmission:/var/lib/transmission-daemon/info
      #set transmission or sonarr download folder to /downloads
      - $HOME/media-server/downloads/complete:/downloads
      - $HOME/media-server/downloads/temp:/var/lib/transmission-daemon/incomplete

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - UMASK_SET=022 #optional
    volumes:
      - $HOME/media-server/config/sonarr:/config
      - #HOME/media-server/storage/series:/tv
      - $HOME/media-server/downloads/complete:/downloads
    ports:
      - 8989:8989
    networks:
      - media-server
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - media-server
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/media-server/config/radarr:/config
      - $HOME/media-server/storage/movies:/movies
      - $HOME/media-server/downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    networks:
      - media-server
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/media-server/config/jackett:/config
      - $HOME/media-server/downloads/blackhole:/downloads

